config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords, :sessions]
  devise_scope :user do
    resource :registration,
      only: [:create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
    resource :password,
      controller: 'users/passwords'
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => 'users/registrations#new', :as => :new_user_registration
    
    
  end
  root 'static_pages#home'
  match '/pricing',    to: 'static_pages#pricing',        via: 'get'
  get 'mentors' => 'users#index', :as => :mentors
  get 'profile/:slug' => 'users#show', :as => :profile
  get 'profile/mentor_chat/:slug' => 'users#mentor_mailing', :as => :mentor_mailing_chat
  get 'profile/express_order/:slug' => 'users#express_order', :as => :express_order
  get 'order/' => 'orders#new', :as => :orders
  post 'order/' => 'orders#create'
  match '/about_us',  to: "static_pages#about_us",        via: 'get'
  match '/disclaimer',  to: "static_pages#disclaimer",        via: 'get'
  match '/our_team',  to: "static_pages#our_team",        via: 'get'
  match '/become_mentor',  to: "static_pages#become_mentor",        via: 'get'
  get 'user_index' => 'users#user_index', :as => :user_index
  get 'user_mentor/:id' => 'users#user_mentor', :as => :user_mentor
  match '/process',    to: 'static_pages#ivyrocket_process',        via: 'get'
  match '/contact_us',    to: 'static_pages#contact_us',        via: 'get'
  match '/ivyrocket',   to: 'users#ivyrocket_chat',    via: 'get'
  match '/ivyrocket_chat', to: 'users#ivyrocket_mailing', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  rolify
  before_create :set_default_role
  before_save :set_slug, :if => :user_is_mentor
  mount_uploader :avatar, AvatarUploader
  validates :name, uniqueness: true
  validates_presence_of	:bio,
    		:school_name,
    		:degree_year,
    		:hometown,
    		:field_of_study,
    		:major,
    		:applied_early,
    		:SAT_total,
    		:class_rank,
    		#:main_high_school_awards,
    		:main_extracurricular_activities,
    		#:my_strengths,
    		#:my_weaknesses,
    		:why_i_think_i_was_accepted,
    		:biggest_piece_of_advice_to_high_school_students,
        :avatar, :if => :user_is_mentor


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  def set_slug
    self.slug = name.parameterize
  end

  def user_is_mentor
    self.has_role? :mentor
  end

  def to_param
    slug
  end

  private
	  def set_default_role
	    self.add_role :student
	  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  protected
    def after_resetting_password_path_for(resource)
      signed_in_root_path(resource)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
=begin
  def new_mentor
  	if current_user.nil?
  		redirect_to root_url
  	end
  	if current_user.has_role? :admin
	  	build_resource({})
	    respond_with self.resource
	else
		redirect_to root_url
	end
  end

  def create_mentor
  	if current_user.nil?
  		redirect_to root_url
  	end
  	if current_user.has_role? :admin

	  	build_resource(sign_up_params)

	    resource_saved = resource.save
	    yield resource if block_given?
	    if resource_saved
	      if resource.active_for_authentication?
	        set_flash_message :notice, :signed_up if is_flashing_format?
	        sign_up(resource_name, resource)
	        respond_with resource, location: after_sign_up_path_for(resource)
	      else
	        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
	        expire_data_after_sign_in!
	        respond_with resource, location: after_inactive_sign_up_path_for(resource)
	      end
	    else
	      clean_up_passwords resource
	      respond_with resource
	    end
	else
		redirect_to root_url
	end
  end
=end


  protected
  	def sign_up_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

  	def account_update_params
    	params.require(:user).permit(:email, :password, :password_confirmation, :current_password,
    		:name, 
    		:bio, 
    		:school_name,
    		:degree_year,
    		:hometown,
    		:field_of_study,
    		:major,
    		:other_acceptances,
    		:other_waitlists,
    		:applied_early,
    		:SAT_total,
    		:SAT_math,
    		:SAT_reading,
    		:SAT_writing,
    		:ACT_composite,
    		:class_rank,
    		:main_high_school_awards,
    		:main_extracurricular_activities,
    		:job_experience,
    		:volunteer_experience,
    		:summer_activities,
    		:my_strengths,
    		:my_weaknesses,
    		:why_i_think_i_was_accepted,
    		:biggest_piece_of_advice_to_high_school_students,
    		:avatar)
  	end

    def after_sign_up_path_for(resource)
      signed_in_root_path(resource)
    end

    def after_update_path_for(resource)
      signed_in_root_path(resource)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :mentor_mailing, :ivyrocket_chat]

  def index
    mentors = User.with_role :mentor
    mentors_with_avatar = mentors.reject { |x| x.avatar.blank? }
    @users = mentors_with_avatar.shuffle
  end

  def user_index
  	if current_user.nil? || ((current_user.has_role? :admin) == false)
  		flash[:success] = "You do not have access to this page"
  		redirect_to root_url
  	elsif current_user.has_role? :admin
  		@users = User.order('id ASC')
  	end
  end

  def ivyrocket_chat
  	@user = current_user
  end

  def ivyrocket_mailing
  	@user = current_user
  	MentorMailer.ivyrocketchat_email(@user).deliver
  	flash[:success] = "Email successfully sent!"
	redirect_to root_url
  end

  def user_mentor
  	if current_user.nil? || ((current_user.has_role? :admin) == false)
  		flash[:success] = "You do not have access to this page"
  		redirect_to root_url
  	elsif current_user.has_role? :admin
  		user = User.find_by_id!(params[:id])
  		if user.has_role? :mentor
  			user.remove_role :mentor
  			flash[:success] = "#{user.name} removed of mentor role."
  			redirect_to user_index_path
  		elsif !(user.has_role? :mentor)
  			user.add_role :mentor
  			flash[:success] = "#{user.name} made into mentor."
  			redirect_to user_index_path
  		end
  	end
  end

  def show
  	@confirm = params[:confirmation]
  	@first_hour = params[:first_hour]
  	@commonapp = params[:commonapp]
  	@supplement = params[:supplement]
  	@add_hour = params[:add_hour]
  	@complete = params[:complete]
  	@junior = params[:junior]
  	@user = User.find_by_slug!(params[:slug])
  end

  def mentor_mailing
  	@user = current_user
  	if ChatLimit.find_by_email(@user.email).blank?
	  	@mentor = User.find_by_slug(params[:slug])
	  	MentorMailer.freechat_email(@user, @mentor).deliver
	  	MentorMailer.freechat_email_student(@user, @mentor).deliver
	  	flash[:success] = "Email successfully sent!"
	  	ChatLimit.create(email: @user.email, chattimes: 1, chatstamp: Time.now)
	  	puts "HEREHERERERER"
	  	p ChatLimit.find_by_email(@user.email).chattimes
	  	p ChatLimit.find_by_email(@user.email).chatstamp
	  	redirect_to root_url
	elsif ChatLimit.find_by_email(@user.email).chattimes < 4
		@mentor = User.find_by_slug(params[:slug])
	  	MentorMailer.freechat_email(@user, @mentor).deliver
	  	MentorMailer.freechat_email_student(@user, @mentor).deliver
	  	flash[:success] = "Email successfully sent!"
	  	@chat = ChatLimit.find_by_email(@user.email)
	  	@chat.chattimes += 1
	  	@chat.save
	  	redirect_to root_url
	elsif ChatLimit.find_by_email(@user.email).chattimes = 4
		@chat = ChatLimit.find_by_email(@user.email)
		if (Time.now - @chat.chatstamp) / 604800 > 1
			@mentor = User.find_by_slug(params[:slug])
		  	MentorMailer.freechat_email(@user, @mentor).deliver
		  	MentorMailer.freechat_email_student(@user, @mentor).deliver
		  	flash[:success] = "Email successfully sent!"
		  	@chat.chattimes = 1
		  	@chat.chatstamp = Time.now
		  	@chat.save
		  	redirect_to root_url
		else
			flash[:success] = "You have reached your weekly limit of 4 requests to chat. Please check back in a week to request additional chats."
			redirect_to root_url
		end
	end
  end

  def express_order
  	@student = current_user
  	@package = params[:package]
  	@mentor = User.find_by_slug(params[:slug])
  	if @package == 'first hour'
	  	response = EXPRESS_GATEWAY.setup_purchase(4000,
	      :ip => request.remote_ip,
	      :return_url => "http://www.ivyrocket.com/#{orders_path}",
	      :cancel_return_url => "http://www.ivyrocket.com",
	      :subtotal => 4000,
	      :shipping => 0,
	      :handling => 0,
	      :tax =>      0,
	      :items => [{ :name => "#{@mentor.name} | First Hour | #{@student.name}",
	                  :quantity => 1,
	                  :amount   => 4000,
	                  :description => "First hour with #{@mentor.name}"}]
		)
		redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
	elsif @package == 'commonapp'
		mentor_array = @student.orders.map{|x| x[:mentor_id]}
		if mentor_array.include? @mentor.id
			response = EXPRESS_GATEWAY.setup_purchase(9000,
		      :ip => request.remote_ip,
		      :return_url => "http://www.ivyrocket.com/#{orders_path}",
		      :cancel_return_url => "http://www.ivyrocket.com",
		      :subtotal => 9000,
		      :shipping => 0,
		      :handling => 0,
		      :tax =>      0,
		      :items => [{ :name => "#{@mentor.name} | CommonApp | #{@student.name}",
		                  :quantity => 1,
		                  :amount   => 9000,
		                  :description => "CommonApp package with #{@mentor.name}"}]
			)
			redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
		else
			flash[:failure] = "You must purchase the First Hour with #{@mentor.name} before you can purchase this package."
			redirect_to root_path
		end
	elsif @package == 'supplement'
		mentor_array = @student.orders.map{|x| x[:mentor_id]}
		if mentor_array.include? @mentor.id
			response = EXPRESS_GATEWAY.setup_purchase(5000,
		      :ip => request.remote_ip,
		      :return_url => "http://www.ivyrocket.com/#{orders_path}",
		      :cancel_return_url => "http://www.ivyrocket.com",
		      :subtotal => 5000,
		      :shipping => 0,
		      :handling => 0,
		      :tax =>      0,
		      :items => [{ :name => "#{@mentor.name} | Supplement | #{@student.name}",
		                  :quantity => 1,
		                  :amount   => 5000,
		                  :description => "Supplement package with #{@mentor.name}"}]
			)
			redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
		else
			flash[:failure] = "You must purchase the First Hour with #{@mentor.name} before you can purchase this package."
			redirect_to root_path
		end
	elsif @package == 'add hour'
		mentor_array = @student.orders.map{|x| x[:mentor_id]}
		if mentor_array.include? @mentor.id
			response = EXPRESS_GATEWAY.setup_purchase(2500,
		      :ip => request.remote_ip,
		      :return_url => "http://www.ivyrocket.com/#{orders_path}",
		      :cancel_return_url => "http://www.ivyrocket.com",
		      :subtotal => 2500,
		      :shipping => 0,
		      :handling => 0,
		      :tax =>      0,
		      :items => [{ :name => "#{@mentor.name} | Additional Hour | #{@student.name}",
		                  :quantity => 1,
		                  :amount   => 2500,
		                  :description => "Additional hour with #{@mentor.name}"}]
			)
		redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
		else
			flash[:failure] = "You must purchase the First Hour with #{@mentor.name} before you can purchase this package."
			redirect_to root_path
		end
	elsif @package == 'complete'
		response = EXPRESS_GATEWAY.setup_purchase(29999,
	      :ip => request.remote_ip,
	      :return_url => "http://www.ivyrocket.com/#{orders_path}",
	      :cancel_return_url => "http://www.ivyrocket.com",
	      :subtotal => 29999,
	      :shipping => 0,
	      :handling => 0,
	      :tax =>      0,
	      :items => [{ :name => "#{@mentor.name} | Complete Package | #{@student.name}",
	                  :quantity => 1,
	                  :amount   => 29999,
	                  :description => "Complete package with #{@mentor.name}"}]
		)
		redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
	elsif @package == 'junior'
		response = EXPRESS_GATEWAY.setup_purchase(5000,
	      :ip => request.remote_ip,
	      :return_url => "http://www.ivyrocket.com/#{orders_path}",
	      :cancel_return_url => "http://www.ivyrocket.com",
	      :subtotal => 5000,
	      :shipping => 0,
	      :handling => 0,
	      :tax =>      0,
	      :items => [{ :name => "#{@mentor.name} | Junior Package | #{@student.name}",
	                  :quantity => 1,
	                  :amount   => 5000,
	                  :description => "Junior package with #{@mentor.name}"}]
		)
		redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
	end
  end
end

app/views/users/index.html.erb
<div class="profile">
	<br><br>
	<h1 class="welcome-index" style="padding-top:100px">
	Find a Mentor
	</h1>
	<h3 class="white" style="text-align:center; margin: 10px 0 0 0"><br><br>
</h3>





	<div class="row" style="padding-top:0; padding-bottom: 25em">
		<div class="one columns"></div>
		<div class="ten columns">
		
			<ul>
			    <div class="row" style="padding: 20px 0 1em 0">
			    	<div class="twelve columns">
			    		<h2 class="white" style="text-align:center">
			    			Below are a list of our mentors.<br>
			    			You can click on their names to view their full profiles and request a free 20 minute consultation with them. <br><br>
			    			<%= link_to ("You can also click here to request a free 20 minute consultation with the IvyRocket Team!"), "/ivyrocket", class: "index-name"%></h2>
			    		<ul class="index-info">
			    			<li><h2 class="white"></h2></li>
			    			<li><h3 class="white"></h3></li>
			    			
			    			<li><h4 small class="white"></h4></li>
			    		</ul>
					</div>
				</div>
				<HR WIDTH="100%" SIZE="3" NOSHADE>
			</ul>


			<ul>
			  <% length = @users.length %>
			  <% @users.each_with_index do |user, index| %>
			    <div class="row" style="padding: 20px 0 20px 0" >
					<div class="four columns" style="padding-top:10px">
						<%= link_to (image_tag user.avatar.thumb.url), "/profile/#{user.slug}" %></div>
			    	<div class="eight columns">
					
			    		<h1><%= link_to(user.name, "/profile/#{user.slug}", class:"index-name")%></h1>
			    		<ul class="index-info">
			    			<li><h2 class="white"><%= user.school_name %></h2></li>
			    			<li><h3 class="white"><%= user.major %></h3></li>
			    			<% if !user.degree_year.blank? %>
			    			<li><h4 class="white">Class of <%= user.degree_year %></h4></li>
			    			<% end %>
			    			<li><h4 small class="white"><%= user.bio %></h4></li>
			    		</ul>
					</div>
				</div>
				<% if !((index + 1) == length) %><HR WIDTH="100%" SIZE="3" NOSHADE><% end %>
			  <% end %> 
			</ul>
		
		</div>
		<div class="one columns"></div>

	</div>
</div>

app/views/users/user_index.html.erb
<div class="heading pricing">
  <h1 class="welcome_text white">
    Users
  </h1>
  <h3 class="white" style="text-align:center; margin: 10px 0 0 0"><br><br>
  </h3>
</div>

<div class="pricing-background" style="padding-bottom:15em">
	<% if !flash.blank? %>
		<div class = "row">
			<div class="four columns"></div>
			<div class="four columns">
			  <div class="alert-box alert secondary">
			    <h4 style="text-align:center">
			      <% flash.each do |key, value| %>
			        <%= value %>
			      <% end %>
			    </h4>
			  </div>
			</div>
			<div class="four columns"></div>
		</div>
	<% end %>
	<ul>
		<% length = @users.length %>
		<% @users.each_with_index do |user, index| %>
			<div class="row" style="padding-top:1em; padding-bottom:1em">
				<div class="one column"></div>
				<div class="two columns"><%= image_tag user.avatar.thumb.url %></div>
				<div class="three columns" style="text-align:center; padding-top:1em">
					<h1><%= user.name %></h1>
				</div>
				<div class="two columns" style="text-align:center; padding-top:2em">
					<h3>Mentor? <%= user.has_role? :mentor %></h3>
				</div>
				<div class="two columns" style="text-align:center; padding-top:2em">
					<%= link_to "Mentor", user_mentor_path(:id => user.id), {style: 'width:100px; height:50px; font-size:25px; text-align:center', class: "button-splash"}%>
				</div>
				<div class="two columns"></div>
			</div>
			<% if !((index + 1) == length) %><HR WIDTH="100%" SIZE="3" NOSHADE><% end %>
		<% end %>
	</ul>
</div>