config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords, :sessions]
  devise_scope :user do
    resource :registration,
      only: [:create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
    resource :password,
      controller: 'users/passwords'
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => 'users/registrations#new', :as => :new_user_registration
    
    
  end
  root 'static_pages#home'
  match '/pricing',    to: 'static_pages#pricing',        via: 'get'
  get 'mentors' => 'users#index', :as => :mentors
  get 'profile/:slug' => 'users#show', :as => :profile
  get 'profile/mentor_chat/:slug' => 'users#mentor_mailing', :as => :mentor_mailing_chat
  get 'profile/express_order/:slug' => 'users#express_order', :as => :express_order
  get 'order/' => 'orders#new', :as => :orders
  post 'order/' => 'orders#create'
  match '/about_us',  to: "static_pages#about_us",        via: 'get'
  match '/disclaimer',  to: "static_pages#disclaimer",        via: 'get'
  match '/our_team',  to: "static_pages#our_team",        via: 'get'
  match '/become_mentor',  to: "static_pages#become_mentor",        via: 'get'
  get 'user_index' => 'users#user_index', :as => :user_index
  get 'user_mentor/:id' => 'users#user_mentor', :as => :user_mentor
  match '/process',    to: 'static_pages#ivyrocket_process',        via: 'get'
  match '/contact_us',    to: 'static_pages#contact_us',        via: 'get'
  match '/ivyrocket',   to: 'users#ivyrocket_chat',    via: 'get'
  match '/ivyrocket_chat', to: 'users#ivyrocket_mailing', via: 'get'

end

app/views/layouts/_footer.html.erb
<!-- ######################## Section ######################## -->
<div id="footer">
<footer>  
   <section class="section_dark">
   
        <div class="row">
         <div class="three columns" style="text-align:center">
            <h4 class="white"><%= link_to "About Us", '/about_us', class:"other-links"%></h4>
            <p class="white"></p>
         </div>
         
         <div class="three columns" style="text-align:center">
            <h4 class="white"><%= link_to "Contact Us", '/contact_us', class:"other-links"%></h4>
            <p class="white"></p>
         </div>
      
          <div class="three columns" style="text-align:center">
            <h4 class="white"></h4>
            <p class="white">&copy;2014</p>
          </div>
          
          
          <div class="three columns" style="text-align:center">
            <h4 class="white"></h4>
            <p class="white">Founded in Philadelphia, PA</p>
          </div>
        
        </div>
        
    </section>
</footer>
</div>

app/views/layouts/_nav.html.erb
<div class= "fixed">
  <!--
  <nav class="top-bar" data-topbar role="navigation">
    <div class="row">
      <ul class="title-area">
        <li class="name">
          <div style="margin-top: -13px"><%= link_to image_tag('IvyRocketLogo3.png', width:155, height:30), root_path, style:"opacity:1;"%></div>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <li class="active"><a href="#">Right Button Active</a></li>
          <li class="has-dropdown">
            <a href="#">Right Button Dropdown</a>
            <ul class="dropdown">
              <li><a href="#">First link in dropdown</a></li>
              <li class="active"><a href="#">Active link in dropdown</a></li>
            </ul>
          </li>
        </ul>

        <ul class="left">
          <li><a href="#">Left Nav Button</a></li>
        </ul>
      </section>
    </div>
  </nav>
  -->


  <nav class>
     <div class="twelve columns header_nav">
     <div class="row">
        <ul id="menu-header" class="nav-bar horizontal left">
        <div style="margin-top: -13px"><%= link_to image_tag('IvyRocketLogo3.png', width:155, height:30), root_path, style:"opacity:1;"%></div>
        </ul>
        <ul id="menu-header" class="nav-bar horizontal right">
        
          <li><%= link_to "Find a Mentor", mentors_path %></li>
          <li><%= link_to "Pricing", pricing_path %></li>
          <li><%= link_to "The IvyRocket Process", process_path %></li>
          <li><a href="/become_mentor">Become a Mentor</a></li>
          

          <% if user_signed_in? %>
            <li class="has-flyout">
              <% if current_user.has_role? :mentor %>
                <%= link_to "Account", "/profile/#{current_user.slug}" %>
              <% else %>
                <%= link_to "Account", edit_user_registration_path %>
              <% end %>
              <ul class="flyout">
                <% if current_user.has_role? :mentor %>
                  <li class="has-flyout"><%= link_to "Profile", "/profile/#{current_user.slug}" %></li>
                <% end %>
                <li class="has-flyout"><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <% if current_user.has_role? :admin %>
                  <li class="has-flyout"><%= link_to "Users", user_index_path %></li>
                <% end %>
                <li class="has-flyout">
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
      
        </ul>
        
        <script type="text/javascript">
         //<![CDATA[
         $('ul#menu-header').nav-bar();
          //]]>
        </script>
        

        
      </div>  
      </div>
  </nav>
</div>

      <!--
          <li class="has-flyout">
           <a href="#">Example Pages</a><a href="#" class="flyout-toggle"></a>
            <ul class="flyout">
              <li class="has-flyout"><a href="blog.html">Blog</a></li>
              <li class="has-flyout"><a href="blog_single.html">Blog Single Page</a></li>
              <li class="has-flyout"><a href="products-page.html">Products Page</a></li>
              <li class="has-flyout"><a href="product-single.html">Product Single</a></li>
              <li class="has-flyout"><a href="pricing-table.html">Pricing Table</a></li>
              <li class="has-flyout"><a href="contact.html">Contact Page</a></li>
            </ul> 
          </li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "IvyRocket | Shoot for the League!" %></title>
    
    <%= stylesheet_link_tag    "application", media: "all" %>
        
    <!--<%= javascript_include_tag "vendor/modernizr" %>-->
    <%= csrf_meta_tags %>

  </head>
  <div id="wrap">
    <%= render 'layouts/nav' %>
    <% if (((((((((params[:action] == "show" && params[:controller] == "users") || (params[:action] == "new" && params[:controller] == "orders")) || (params[:action] == "index" && params[:controller] == "users")) || (params[:action] == "about_us" && params[:controller] == "static_pages")) || (params[:action] == "disclaimer" && params[:controller] == "static_pages")) || (params[:action] == "our_team" && params[:controller] == "static_pages")) || (params[:action] == "become_mentor" && params[:controller] == "static_pages")) || (params[:action] == "ivyrocket_process" && params[:controller] == "static_pages")) || (params[:action] == "contact_us" && params[:controller] == "static_pages")) || (params[:action] == "ivyrocket_chat" && params[:controller] == "users")%>
      <div class="profile-body" style="margin:0">
    <% end %>
        <body>    
          <%= yield %>
          <%= javascript_include_tag "application" %>
        </body>
    <% if (((((((((params[:action] == "show" && params[:controller] == "users") || (params[:action] == "new" && params[:controller] == "orders")) || (params[:action] == "index" && params[:controller] == "users")) || (params[:action] == "about_us" && params[:controller] == "static_pages")) || (params[:action] == "disclaimer" && params[:controller] == "static_pages")) || (params[:action] == "our_team" && params[:controller] == "static_pages")) || (params[:action] == "become_mentor" && params[:controller] == "static_pages")) || (params[:action] == "ivyrocket_process" && params[:controller] == "static_pages")) || (params[:action] == "contact_us" && params[:controller] == "static_pages")) || (params[:action] == "ivyrocket_chat" && params[:controller] == "users")%>
      </div>
    <% end %>
    <!--<%= debug(params) if Rails.env.development? %>-->
  </div>

  <%= render 'layouts/footer' unless ((!current_user.nil? && (current_user.has_role? :mentor)) && current_page?('/users/edit')) %>

</html>